### ISSUE TITLE
10_show list of sport locations

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone__userStories#2]
## Value Proposition

**As a** user 

**I need** to see a list of sport locations

**to be able to** choose a place where I can do sport

## Description

Scribble / design or text

## Acceptance Criteria

- [ ] describe every scenario in detail
- [ ] e.g. All Inputs are required, show warning if empty.
- [ ] show list of sport locations
- [ ] has header and footer

## Tasks

(for developers team)

- [ ] list the tasks that need to be performend within the dev team
- [ ] e.g. Components, Storybook, testing
- [ ] create new project with create next-app
- [ ] connect project with github
- [ ] clean up folder

- [ ] add basic styling (e.g. *box-sizing: border-box)
- [ ] make mobile design in globalstyles

- [ ] create dummy locations
- [ ] data should be stored in state
- [ ] render list 
- [ ] create pull request

**Comment by andy-schwedler** [comment]
Top, alles dabei für einen großartigen Start. Vielleicht kosmetisch, würd ich mir als Sportler eher "Kacheln" anstatt "Blöcke" verwenden. Es sei denn, du möchtest in den kommenden Sprints noch mehr infos anzeigen...just saying.

**Comment by marvinRoellecke** [comment]
Danke für den Hinweis Andy. 
Kacheln finde ich auch schön. Ich weiß nur noch nicht wie viel Platz eine Kachel oder Block final einnimmt, da ich noch kein detailliertes Design habe. Vielleicht auch ein Mix und dass es sich automatisch nach Platzbedarf anpasst

**Comment by julialoeschel** [comment]
Hey, sieht super aus. 
Ich glaube du brauchst hier den Footer noch garnicht, der hat keinen Mehrwert für den Nutzer an der Stelle. 

sonst 👍
