### ISSUE TITLE
11_show more information at list items__draft

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone__userStories#4]
## Value Proposition

**As a** user 

**I need** to see a detailed information of sport locations

**to be able to** better choose a place where I can do sport

## Description

![11-show more info at list items](https://user-images.githubusercontent.com/115343305/206722526-347b7bbf-08ac-48f7-bb78-551212896072.png)

## Acceptance Criteria

- [ ] show list items with more information of sport locations
- [ ] has header and footer
- [ ] list items should be components

## Tasks

- [ ] update dummy array for locations with more information
- [ ] insert example pictures from unsplash
- [ ] style card with storybook
- [ ] use styledComponents 
- [ ] create pull request

**Comment by flipkoehler** [comment]
Hey Marvin, 
ebenfalls schöne Story und schöner erster Inhalte :) 
Ich würde in den AKs noch ergänzen welche Daten angezeigt werden sollen (Headline, Bild...) und ggf. noch die Eigenschaften (z.B. Textlänge max. 200 Zeichen) 
Header und Footer sind nicht Bestandteil des Tickets, oder?

**Comment by julialoeschel** [comment]
Hello :) 
gute 2. Story. 

Mir fehlt die Info, wie man die Karte ausklappt (wenn man draufdrückt? oder gibts ein Button? ) 
und klappt sich die Karte wieder ein später? nach einer bestimmten Zeit oder gibts hier einen button? 
;) 
Evt könnte man bedenken, was man macht wenn der Text zu lang ist, es mehr als 2 Tags gibt oder die Adresse länger ist als das Feld. Das wäre teil der ACs.

Storybookk gehört eher in die Tasks.
Und genau - der footer wieder :) brauchen wir noch nicht, kann raus ;)

**Comment by marvinRoellecke** [comment]
Vielen Dank für euer Feedback.
die Karten sind noch nicht klickbar. Diese sollen später auf einer einzelnen Seite über den ganzen Viewport angezeigt werden.
