### ISSUE TITLE
13-filter and sort list items--draft

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone__userStories#6]
## Value Proposition

**As a** user 

**I need** to see a detailed information of sport locations

**to be able to** better choose a place where I can do sport

## Description

![13-filter and sort list items](https://user-images.githubusercontent.com/115343305/206901239-a0531cfe-b3fe-46eb-83a1-df9d152fd2a4.png)

## Acceptance Criteria

- [ ] show list items with more information of sport locations
         [title, tags, rating, address, image url]

## Tasks

(for developers team)

- [ ] update dummy array for locations with more information [title, tags, rating, address, image url]
    max. 2 tags, address showing city or district only
- [ ] insert example pictures from unsplash
- [ ] style card component with storybook
- [ ] use styledComponents 
- [ ] create pull request
