### ISSUE TITLE
14-add favorite button

### ISSUE THREAD

**Issue by marvinRoellecke** [marvinRoellecke/capstone__userStories#8]
## Value Proposition

**As a** user 

**I want** to mark an list item as favorite

**to be able to** note places that I visit frequently

## Description

![14-add favorite button](https://user-images.githubusercontent.com/115343305/206919779-c96d9d1a-5794-486e-8c81-053392f77a5f.png)

## Acceptance Criteria

- [ ] favorite button on list item
- [ ] favorite button on details page
- [ ] favorite button is clickable and changes style when checked

## Tasks

(for developers team)

- [ ] add favorite button on list item
- [ ] add favorite button on details page
- [ ] make button a component and use it on list item and details page
- [ ] change style when checked
- [ ] update state when checked
- [ ] create pull request
